;;; Core data model for the pure REPL input reducer.

(in-package #:nshell.presentation)

(defmacro define-input-state-constructor (fields)
  (let ((lambda-list '())
        (constructor-arguments '()))
    (dolist (field fields)
      (destructuring-bind (name default) field
        (push (if (null default) name `(,name ,default)) lambda-list)
        (push (intern (symbol-name name) :keyword) constructor-arguments)
        (push name constructor-arguments)))
    `(defun make-input-state (&key ,@(nreverse lambda-list))
       (%make-input-state ,@(nreverse constructor-arguments)))))

(define-input-state-constructor
  ((buffer "")
   (cursor-pos 0)
   (completion-index -1)
   (completion-base-buffer nil)
   (completion-base-cursor nil)
   (last-candidates nil)
   (suggestion nil)
   (mode :insert)
   (vi-count nil)
   (vi-visual-anchor nil)
   (mouse-selection-anchor nil)
   (mouse-selection-end nil)
   (abbreviation-expander nil)
   (kill-ring nil)
   (last-yank-start nil)
   (last-yank-end nil)
   (last-yank-index nil)
   (last-argument-start nil)
   (last-argument-end nil)
   (last-argument-index nil)
   (search-query "")
   (search-original-buffer "")
   (search-original-cursor nil)
   (search-index 0)
   (undo-stack nil)
   (redo-stack nil)))
