;;; Data definitions for pure REPL input dispatch.

(in-package #:nshell.presentation)

(define-value-struct %input-dispatch-action
    ((kind :none :type symbol)
     (value nil :optional t)))

(define-value-struct %input-dispatch-transition
    ((state nil)
     (output :none :type symbol)))

(defparameter +input-dispatch-action-table+
  ;; ACTION-NAME -> (KIND VALUE), the pair INPUT-DISPATCH-ACTION-FOR-KEY-EVENT
  ;; passes to %MAKE-INPUT-DISPATCH-ACTION. Most actions carry no value; the
  ;; ones that do (:CYCLE-COMPLETION, :MOVE-CURSOR, :MOVE-CURSOR-ABSOLUTE,
  ;; :EMIT) had a single value at every call site in the case this table
  ;; replaced, so that value is fixed here under a name distinct from the
  ;; internal KIND. The BIND builtin's set of valid action names is exactly
  ;; the first column.
  '((:none :none nil)
    (:enter :enter nil)
    (:cycle-completion-next :cycle-completion 1)
    (:cycle-completion-prev :cycle-completion -1)
    (:backspace :backspace nil)
    (:delete :delete nil)
    (:clear-input :clear-input nil)
    (:delete-or-quit :delete-or-quit nil)
    (:start-ask :start-ask nil)
    (:start-history-search :start-history-search nil)
    (:accept-suggestion :accept-suggestion nil)
    (:escape :escape nil)
    (:redraw-clearing-completion :redraw-clearing-completion nil)
    (:move-cursor-left :move-cursor -1)
    (:move-cursor-start :move-cursor-absolute 0)
    (:move-eol-or-accept-suggestion :move-eol-or-accept-suggestion nil)
    (:kill-to-eol :kill-to-eol nil)
    (:clear-screen :emit :clear-screen)
    (:edit-command :emit :edit-command)
    (:history-next :emit :history-next)
    (:history-prev :emit :history-prev)
    (:transpose-chars :transpose-chars nil)
    (:kill-to-bol :kill-to-bol nil)
    (:backward-kill-word :backward-kill-word nil)
    (:yank-last-kill :yank-last-kill nil)
    (:undo :undo nil)
    (:redo :redo nil)
    (:insert-last-argument :emit :insert-last-argument)
    (:capitalize-word :capitalize-word nil)
    (:downcase-word :downcase-word nil)
    (:transpose-words :transpose-words nil)
    (:upcase-word :upcase-word nil)
    (:cycle-last-yank :cycle-last-yank nil)
    (:move-word-left :move-word-left nil)
    (:accept-suggestion-word :accept-suggestion-word nil)
    (:forward-kill-word :forward-kill-word nil)
    (:toggle-sudo-prefix :toggle-sudo-prefix nil)
    (:redraw :redraw nil)))

(defparameter +default-input-dispatch-bindings+
  ;; KEY-EVENT-TYPE -> ACTION-NAME, the bindings BIND --reset restores.
  ;; :CHAR, :PASTE, and :MOUSE key-event types carry per-event data and are
  ;; handled outside this table by INPUT-DISPATCH-ACTION-FOR-KEY-EVENT, so
  ;; they are not bindable keys.
  '((:enter . :enter)
    (:tab . :cycle-completion-next)
    (:shift-tab . :cycle-completion-prev)
    (:backspace . :backspace)
    (:delete . :delete)
    (:ctrl-c . :clear-input)
    (:ctrl-d . :delete-or-quit)
    (:ctrl-right-bracket . :start-ask)
    (:ctrl-r . :start-history-search)
    (:ctrl-s . :start-history-search)
    (:ctrl-f . :accept-suggestion)
    (:right . :accept-suggestion)
    (:escape . :escape)
    (:ctrl-g . :redraw-clearing-completion)
    (:ctrl-b . :move-cursor-left)
    (:left . :move-cursor-left)
    (:ctrl-a . :move-cursor-start)
    (:home . :move-cursor-start)
    (:ctrl-e . :move-eol-or-accept-suggestion)
    (:end . :move-eol-or-accept-suggestion)
    (:ctrl-k . :kill-to-eol)
    (:ctrl-l . :clear-screen)
    (:alt-e . :edit-command)
    (:ctrl-n . :history-next)
    (:down . :history-next)
    (:page-down . :history-next)
    (:ctrl-p . :history-prev)
    (:up . :history-prev)
    (:page-up . :history-prev)
    (:ctrl-t . :transpose-chars)
    (:ctrl-u . :kill-to-bol)
    (:ctrl-w . :backward-kill-word)
    (:ctrl-y . :yank-last-kill)
    (:ctrl-underscore . :undo)
    (:alt-r . :redo)
    (:alt-dot . :insert-last-argument)
    (:alt-c . :capitalize-word)
    (:alt-l . :downcase-word)
    (:alt-t . :transpose-words)
    (:alt-u . :upcase-word)
    (:alt-y . :cycle-last-yank)
    (:alt-left . :move-word-left)
    (:ctrl-left . :move-word-left)
    (:alt-b . :move-word-left)
    (:alt-right . :accept-suggestion-word)
    (:ctrl-right . :accept-suggestion-word)
    (:alt-f . :accept-suggestion-word)
    (:alt-backspace . :backward-kill-word)
    (:alt-d . :forward-kill-word)
    (:alt-s . :toggle-sudo-prefix)
    (:shift-up . :redraw) (:shift-down . :redraw)
    (:shift-left . :redraw) (:shift-right . :redraw)
    (:alt-up . :redraw) (:alt-down . :redraw)
    (:ctrl-up . :redraw) (:ctrl-down . :redraw)
    (:shift-alt-up . :redraw) (:shift-alt-down . :redraw)
    (:shift-alt-left . :redraw) (:shift-alt-right . :redraw)
    (:shift-ctrl-up . :redraw) (:shift-ctrl-down . :redraw)
    (:shift-ctrl-left . :redraw) (:shift-ctrl-right . :redraw)
    (:alt-ctrl-up . :redraw) (:alt-ctrl-down . :redraw)
    (:alt-ctrl-left . :redraw) (:alt-ctrl-right . :redraw)
    (:shift-alt-ctrl-up . :redraw) (:shift-alt-ctrl-down . :redraw)
    (:shift-alt-ctrl-left . :redraw) (:shift-alt-ctrl-right . :redraw)))

(defvar *input-dispatch-bindings*
  (let ((table (make-hash-table :test 'eq)))
    (dolist (entry +default-input-dispatch-bindings+ table)
      (setf (gethash (car entry) table) (cdr entry))))
  "Hash table from key-event type to action name. Seeded from
+DEFAULT-INPUT-DISPATCH-BINDINGS+ and mutated by the BIND builtin; a type
absent from this table (including one erased by BIND -e) dispatches :NONE.")
