(in-package #:nshell.presentation)

(defvar *running* nil)
(defvar *last-exit-code* 0)
(defvar *pipefail* nil)
(defvar *last-command-duration-ms* nil)
(defvar *last-command-output* nil)
(defvar *history* nil)
(defvar *config* nil)
(defvar *kb* nil)
(defvar *input-state* nil)
(defvar *assistant-turn-generation* 0)
(defvar *assistant-turn-started-at* nil)
(defvar *assistant-last-cancel-at* nil)
(defconstant +assistant-cancel-window-ticks+
  (* 2 internal-time-units-per-second))
(defvar *last-assistant-model-event* nil)
(defvar *assistant-model-event-handler* nil)
(defvar *assistant-request-kind* nil)
(defvar *assistant-explain-candidates* nil)
(defvar *assistant-explain-candidate-index* 0)
(defvar *assistant-command-origin* :typed)
(defvar *assistant-command-confirmed-p* nil)
(defvar *agent-session* nil)
(defvar *command-not-found-fallback-text* nil)
(defvar *command-not-found-command* nil)
(defvar *failure-explain-available-p* nil)
(defvar *completion-rendered-lines* 0)
(defvar *transient-panel-rendered-lines* 0)
(defvar *prompt-rendered-lines* 0)
(defvar *prompt-rendered-cursor-row* 0)
(defvar *prompt-rendered-terminal-width* +default-terminal-width+)
(defvar *prompt-rendered-prompt-width* 0)
(defvar *prompt-rendered-origin-row* 1)
(defvar *prompt-rendered-origin-column* 1)
(defvar *prompt-rendered-origin-known-p* nil)
(defvar *interactive-terminal-installed-p* nil)
(defvar *environment* nil)
(defvar *aliases* (%make-repl-name-table))
(defvar *abbreviations* (%make-repl-name-table))
(defvar *functions* (%make-repl-name-table))
(defvar *function-sources* (%make-repl-name-table))
(defvar *proc-registry* (%make-repl-process-registry)
  "Maps job-id -> SBCL process object or process list for status checking.")
(defvar *completion-help-cache* (make-hash-table :test #'equal))
