(in-package #:nshell.infrastructure.terminal)

;;; The escape-sequence vocabulary is provided by cl-tty-kit, whose ANSI helpers
;;; return strings.  nshell's helpers keep their side-effecting, stream-writing
;;; signatures (callers are unchanged) but delegate the actual byte sequence to
;;; cl-tty-kit, so there is a single source of truth for terminal control codes.
;;; Every sequence below was verified byte-identical to the previous hand-rolled
;;; output (see integration/test-terminal-ansi), including the SGR-mouse ordering.
(defun ansi-clear-screen () (write-string (cl-tty-kit:ansi-clear-screen 2)))
(defun ansi-clear-line () (write-string (cl-tty-kit:ansi-clear-line 2)))
(defun ansi-move-cursor (row col) (write-string (cl-tty-kit:ansi-move-cursor row col)))
(defun ansi-save-cursor (&optional (stream *standard-output*))
  (write-string (cl-tty-kit:ansi-save-cursor) stream))
(defun ansi-restore-cursor (&optional (stream *standard-output*))
  (write-string (cl-tty-kit:ansi-restore-cursor) stream))
(defun ansi-hide-cursor (&optional (stream *standard-output*))
  (write-string (cl-tty-kit:ansi-hide-cursor) stream))
(defun ansi-show-cursor (&optional (stream *standard-output*))
  (write-string (cl-tty-kit:ansi-show-cursor) stream))
(defun ansi-enable-bracketed-paste (&optional (stream *standard-output*))
  (write-string (cl-tty-kit:ansi-enable-bracketed-paste) stream))
(defun ansi-disable-bracketed-paste (&optional (stream *standard-output*))
  (write-string (cl-tty-kit:ansi-disable-bracketed-paste) stream))
(defun ansi-enable-sgr-mouse (&optional (stream *standard-output*))
  (write-string (cl-tty-kit:ansi-enable-mouse :normal) stream))
(defun ansi-disable-sgr-mouse (&optional (stream *standard-output*))
  (write-string (cl-tty-kit:ansi-disable-mouse :normal) stream))
(defun ansi-enable-alternate-screen (&optional (stream *standard-output*))
  (write-string (cl-tty-kit:ansi-enter-alternate-screen) stream))
(defun ansi-disable-alternate-screen (&optional (stream *standard-output*))
  (write-string (cl-tty-kit:ansi-exit-alternate-screen) stream))

(defconstant +base64-alphabet+
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")

(defun %utf-8-octets (text)
  (let ((octets (make-array (* 4 (length text))
                            :element-type '(unsigned-byte 8)))
        (count 0))
    (flet ((emit (octet)
             (setf (aref octets count) octet)
             (incf count)))
      (loop for character across text
            for code = (char-code character)
            do (cond
                 ((<= code #x7f)
                  (emit code))
                 ((<= code #x7ff)
                  (emit (logior #xc0 (ash code -6)))
                  (emit (logior #x80 (logand code #x3f))))
                 ((or (<= code #xd7ff)
                      (<= #xe000 code #xffff))
                  (emit (logior #xe0 (ash code -12)))
                  (emit (logior #x80 (logand (ash code -6) #x3f)))
                  (emit (logior #x80 (logand code #x3f))))
                 ((and (<= #x10000 code)
                       (<= code #x10ffff))
                  (emit (logior #xf0 (ash code -18)))
                  (emit (logior #x80 (logand (ash code -12) #x3f)))
                  (emit (logior #x80 (logand (ash code -6) #x3f)))
                  (emit (logior #x80 (logand code #x3f))))
                 (t
                  (error "Cannot encode character U+~8,'0X as UTF-8."
                         code)))))
    (subseq octets 0 count)))

(defun %base64-encode-octets (octets)
  (with-output-to-string (output)
    (loop for index from 0 below (length octets) by 3
          for remaining = (- (length octets) index)
          for first = (aref octets index)
          for second = (if (> remaining 1)
                           (aref octets (1+ index))
                           0)
          for third = (if (> remaining 2)
                          (aref octets (+ index 2))
                          0)
          for triple = (logior (ash first 16)
                               (ash second 8)
                               third)
          do (write-char (char +base64-alphabet+ (ldb (byte 6 18) triple))
                         output)
             (write-char (char +base64-alphabet+ (ldb (byte 6 12) triple))
                         output)
             (write-char (if (> remaining 1)
                             (char +base64-alphabet+ (ldb (byte 6 6) triple))
                             #\=)
                        output)
             (write-char (if (> remaining 2)
                             (char +base64-alphabet+ (ldb (byte 6 0) triple))
                             #\=)
                        output))))

(defun ansi-copy-to-clipboard (text &optional (stream *standard-output*))
  (write-char #\Esc stream)
  (write-string "]52;c;" stream)
  (write-string (%base64-encode-octets (%utf-8-octets text)) stream)
  (write-char #\Bell stream))

(defun ansi-color-code (color)
  (let ((map '(("00FF00" . 2) ("00AFFF" . 4) ("FF0000" . 1) ("FFFF00" . 3)
               ("FFA500" . 3) ("555555" . 8) ("737373" . 8) ("FFFFFF" . 7))))
    (or (cdr (assoc color map :test #'string=)) 7)))
