; Derived fact and rule generators: build completion data from the static catalogs.
(in-package #:nshell.domain.completion)

(defun builtin-command-flag-facts ()
  (mapcan (lambda (entry)
            (let ((command (getf entry :command))
                  (flags (getf entry :flags)))
              (mapcar (lambda (flag)
                        (list 'has-flag command flag))
                      flags)))
          +builtin-command-catalog+))

(defun catalog-subcommand-name (subcommand)
  (if (consp subcommand)
      (getf subcommand :name)
      subcommand))

(defun catalog-subcommand-description (subcommand)
  (when (consp subcommand)
    (getf subcommand :description)))

(defun external-command-rule-facts ()
  (mapcan (lambda (entry)
            (let ((command (getf entry :command))
                  (description (getf entry :description))
                  (subcommands (getf entry :subcommands))
                  (flags (getf entry :flags)))
              (append (list (list 'completes command command)
                            (list 'describes command description))
                      (mapcar (lambda (subcommand)
                                (list 'completes command
                                      (catalog-subcommand-name subcommand)))
                              subcommands)
                      (mapcan (lambda (subcommand)
                                (let ((name (catalog-subcommand-name subcommand))
                                      (description (catalog-subcommand-description subcommand)))
                                  (when description
                                    (list (list 'describes name description)))))
                              subcommands)
                      (mapcar (lambda (flag)
                                (list 'has-flag command flag))
                              flags))))
          +external-command-catalog+))

(defun builtin-help-entries ()
  (mapcar (lambda (entry)
            (list :command (getf entry :command)
                  :synopsis (getf entry :synopsis)
                  :description (getf entry :description)))
          +builtin-command-catalog+))

(defun completion-command-specs-from-catalog (catalog)
  (mapcar (lambda (entry)
            (let ((command (getf entry :command))
                  (subcommands (getf entry :subcommands))
                  (flags (getf entry :flags))
                  (option-values (getf entry :option-values))
                  (exclusive-options (getf entry :exclusive-options))
                  (description (getf entry :description)))
              (append (list command)
                      (when subcommands
                        (list :subcommands
                              (mapcar #'catalog-subcommand-name subcommands)))
                      (when flags (list :flags flags))
                      (when option-values (list :option-values option-values))
                      (when exclusive-options
                        (list :exclusive-options exclusive-options))
                      (when description (list :description description)))))
          catalog))

(defun builtin-completion-command-specs ()
  (completion-command-specs-from-catalog +builtin-command-catalog+))

(defun external-completion-command-specs ()
  (completion-command-specs-from-catalog +external-command-catalog+))

(defun builtin-rule-facts ()
  (append
   '((command-is "cd" "cd")
     (command-is "source" "source")
     (command-is "." "source"))
   (mapcan (lambda (entry)
             (let ((command (getf entry :command))
                   (description (getf entry :description)))
               (list (list 'completes command command)
                     (list 'describes command description))))
           +builtin-command-catalog+)
   (builtin-command-flag-facts)
   (external-command-rule-facts)
   '((describes "--help" "show command help"))))

(defun builtin-rule-rules ()
  '(((suggests-dir ?input)
     (command-is ?input "cd"))
    ((completes ?cmd "--help")
     (has-flag ?cmd "--help"))
    ((completes ?cmd ?flag)
     (has-flag ?cmd ?flag))
    ((suggests-file ?input)
     (command-is ?input "source"))))
