(in-package #:nshell.application)

(defun %printf-parse-integer (argument)
  (handler-case
      (values (parse-integer argument :junk-allowed nil) t)
    (error () (values 0 nil))))

(defun %printf-parse-real (argument)
  (handler-case
      (let ((*read-eval* nil))
        (multiple-value-bind (value position)
            (read-from-string argument nil nil)
          (if (and (realp value)
                   (= position (length argument)))
              (values (coerce value 'double-float) t)
              (values 0d0 nil))))
    (error () (values 0d0 nil))))

(defun %printf-integer-text (number conversion flags precision)
  (let* ((negative (minusp number))
         (unsigned (if negative (abs number) number))
         (base (cond
                 ((or (char= conversion #\x)
                      (char= conversion #\X))
                  16)
                 ((char= conversion #\o) 8)
                 (t 10)))
         (digits (cond
                   ((= base 16) (format nil "~x" unsigned))
                   ((= base 8) (format nil "~o" unsigned))
                   (t (format nil "~d" unsigned))))
         (digits (if (char= conversion #\X)
                     (string-upcase digits)
                     digits))
         (digits (if precision
                     (concatenate 'string
                                  (make-string (max 0 (- precision (length digits)))
                                               :initial-element #\0)
                                  digits)
                     digits))
         (prefix (if (and (%printf-flag-p flags #\#)
                         (not (zerop unsigned)))
                     (cond
                       ((char= conversion #\x) "0x")
                       ((char= conversion #\X) "0X")
                       ((char= conversion #\o) "0")
                       (t ""))
                     ""))
         (sign (cond
                 (negative "-")
                 ((%printf-flag-p flags #\+) "+")
                 ((%printf-flag-p flags #\Space) " ")
                 (t ""))))
    (concatenate 'string sign prefix digits)))

(defun %printf-format-real (argument conversion flags width precision)
  (multiple-value-bind (number valid-p) (%printf-parse-real argument)
    (let* ((digits (or precision 6))
           (text (cond
                   ((or (char= conversion #\e)
                        (char= conversion #\E))
                    (format nil "~,ve" digits number))
                   ((or (char= conversion #\g)
                        (char= conversion #\G))
                    (format nil "~,vg" digits number))
                   (t (format nil "~,vF" digits number))))
           (text (if (and (member conversion '(#\E #\G))
                          (position #\e text))
                     (substitute #\E #\e text)
                     text))
           (text (if (and (not (minusp number))
                          (%printf-flag-p flags #\+))
                     (concatenate 'string "+" text)
                     (if (and (not (minusp number))
                              (%printf-flag-p flags #\Space))
                         (concatenate 'string " " text)
                         text))))
      (values (%printf-pad text width (%printf-flag-p flags #\-)
                           (if (and (%printf-flag-p flags #\0)
                                    (not (%printf-flag-p flags #\-)))
                               #\0
                               #\Space))
              valid-p
              nil))))
