(in-package #:nshell.application)

(nshell.util:define-value-struct %complete-parse-state
    ((command nil) (flags nil :copy :list) (long-options nil :copy :list)
     (short-options nil :copy :list) (arguments nil :copy :list)
     (description nil) (erase nil))
  :constructor %allocate-complete-parse-state :public-accessors nil)

(defun %make-complete-parse-state ()
  (%allocate-complete-parse-state nil nil nil nil nil nil nil))

(defun %complete-option-spec (option)
  (cdr (assoc option +complete-option-specs+ :test #'string=)))

(defun %complete-long-option-name (option)
  (if (and (>= (length option) 2) (string= option "--" :end1 2))
      option (concatenate 'string "--" option)))

(defun %complete-short-option-name (option)
  (if (and (plusp (length option)) (char= (char option 0) #\-))
      option (concatenate 'string "-" option)))

(defun %complete-argument-values (arguments)
  (remove-if (lambda (value) (string= value ""))
             (host-kit:split-string arguments
                                    :separator (list #\Space #\Tab #\Newline))))

(defun %complete-apply-option-value (spec state value)
  (let ((kind (getf spec :kind)))
    (ecase kind
      (:command (%allocate-complete-parse-state value
                 (%complete-parse-state-flags state)
                 (%complete-parse-state-long-options state)
                 (%complete-parse-state-short-options state)
                 (%complete-parse-state-arguments state)
                 (%complete-parse-state-description state)
                 (%complete-parse-state-erase state)))
      (:flag (%allocate-complete-parse-state (%complete-parse-state-command state)
              (cons value (%complete-parse-state-flags state))
              (%complete-parse-state-long-options state)
              (%complete-parse-state-short-options state)
              (%complete-parse-state-arguments state)
              (%complete-parse-state-description state)
              (%complete-parse-state-erase state)))
      (:long-option (%allocate-complete-parse-state (%complete-parse-state-command state)
                    (%complete-parse-state-flags state)
                    (cons (%complete-long-option-name value)
                          (%complete-parse-state-long-options state))
                    (%complete-parse-state-short-options state)
                    (%complete-parse-state-arguments state)
                    (%complete-parse-state-description state)
                    (%complete-parse-state-erase state)))
      (:short-option (%allocate-complete-parse-state (%complete-parse-state-command state)
                     (%complete-parse-state-flags state)
                     (%complete-parse-state-long-options state)
                     (cons (%complete-short-option-name value)
                           (%complete-parse-state-short-options state))
                     (%complete-parse-state-arguments state)
                     (%complete-parse-state-description state)
                     (%complete-parse-state-erase state)))
      (:arguments (%allocate-complete-parse-state (%complete-parse-state-command state)
                   (%complete-parse-state-flags state)
                   (%complete-parse-state-long-options state)
                   (%complete-parse-state-short-options state)
                   (append (%complete-parse-state-arguments state)
                           (%complete-argument-values value))
                   (%complete-parse-state-description state)
                   (%complete-parse-state-erase state)))
      (:description (%allocate-complete-parse-state (%complete-parse-state-command state)
                      (%complete-parse-state-flags state)
                      (%complete-parse-state-long-options state)
                      (%complete-parse-state-short-options state)
                      (%complete-parse-state-arguments state) value
                      (%complete-parse-state-erase state)))
      (:erase (%allocate-complete-parse-state (%complete-parse-state-command state)
               (%complete-parse-state-flags state)
               (%complete-parse-state-long-options state)
               (%complete-parse-state-short-options state)
               (%complete-parse-state-arguments state)
               (%complete-parse-state-description state) t)))))

(defun %complete-apply-option (spec remaining state)
  (let ((value (second remaining)))
    (values (%complete-apply-option-value spec state value)
            (if (eq (getf spec :kind) :erase) (cdr remaining) (cddr remaining)))))

(defun %complete-state->values (state)
  (values (%complete-parse-state-command state) (%complete-parse-state-flags state)
          (%complete-parse-state-long-options state)
          (%complete-parse-state-short-options state)
          (%complete-parse-state-arguments state)
          (%complete-parse-state-description state) (%complete-parse-state-erase state)))

(defun %complete-parse-error (message)
  (values nil nil nil nil nil nil nil message))

(defun %parse-complete-args (args)
  (labels ((unknown (option) (%complete-parse-error
                              (format nil "complete: unknown option ~a" option)))
           (missing (option spec) (%complete-parse-error
                                   (%required-argument-error "complete" option
                                                              (getf spec :requirement))))
           (finalize (state)
             (multiple-value-bind (command flags long short arguments description erase)
                 (%complete-state->values state)
               (values command (nreverse flags) (nreverse long) (nreverse short)
                       arguments description erase nil)))
           (parse (remaining state)
             (if (endp remaining) (finalize state)
                 (let ((option (first remaining)))
                   (cond ((string= option "--") (finalize state))
                         ((%builtin-option-like-p option)
                          (let ((spec (%complete-option-spec option)))
                            (if spec
                                (if (or (null (getf spec :requirement)) (rest remaining))
                                    (multiple-value-bind (next rest)
                                        (%complete-apply-option spec remaining state)
                                      (parse rest next))
                                    (missing option spec))
                                (unknown option))))
                         (t (finalize state)))))))
    (parse args (%make-complete-parse-state))))
